#!/bin/bash
########################################################################
# Actions to be excecuted once the application has been deployed, but
# not yet started.
########################################################################

# Add database seed values
cd $OPENSHIFT_REPO_DIR
rake db:seed

