#!/bin/bash
########################################################################
# Actions to be excecuted once the application has been deployed, but
# not yet started.
########################################################################

# Add database seed values
cd $OPENSHIFT_REPO_DIR

if [ "$ADMIN_FIRST_NAME" ] ; then
	rake RAILS_ENV=production db:seed
else
	echo "No administrative user variables found. Skipping database seeding."
fi

